name: whisper-asr
title: Whisper ASR
summary: Local Speech-to-Text (STT) using Whisper ASR inference snap
description: |
  This snap provides a local speech-to-text (STT) solution using OpenAI's Whisper models.
  
  It uses the WhisperLive for real-time transcription and provides an OpenAI adapter for exposing an OpenAI-like Realtime Transcription API.
website: https://documentation.ubuntu.com/inference-snaps
source-code: https://github.com/canonical/whisper-snap
issues: https://github.com/canonical/inference-snaps/issues

base: core24
adopt-info: version

grade: devel
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64: 

hooks:
  install:
    plugs: &install-plugs
      # For hardware detection
      - hardware-observe
      - opengl
  post-refresh:
    plugs: *install-plugs

slots:
  stt-inference:
    interface: content
    content: stt-inference
    source:
      write:
        - &inference-share $SNAP_COMMON/share/inference

environment:
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR
  INFERENCE_SHARE: *inference-share # Inference directory shared via content interface
  # This is to find the intel.icd file, containing the path to libigdrcl.so
  # Required for Intel GPU detection and communication
  OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

layout:
  # OpenCL looks in /etc/OpenCL/vendors for .icd files containing the paths to shared objects
  /etc/OpenCL/vendors:
    bind: $SNAP/etc/OpenCL/vendors
  # Intel icd files use an absolute path to Intel OpenCL shared objects. Use a layout to mount the so files at the expected location
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
  # Under wsl the libraries are expected in /usr/lib/wsl
  /usr/lib/wsl:
    bind: $SNAP_COMMON/usr/lib/wsl

parts:
  scripts:
    plugin: dump
    source: ./scripts
    stage-packages:
      - jq
    organize:
      whisper-live-server.sh: bin/whisper-live-server
      openai-adapter.sh: bin/openai-adapter
      whisper-live-server.py: (component/whisper-live)/bin/whisper-live-server.py
      # TODO: there's no "export-shared-configs" script

  version:
    after: [cli]
    plugin: nil
    source: . # To regenerate the git hash on every change
    build-packages:
      - jq
      - git
    override-pull: |
      # Do nothing. This significantly reduces build time when sourcing large files.
    override-build: |
      set -eo pipefail
      cli_version=$($CRAFT_STAGE/bin/modelctl version --format=json | jq .cli --raw-output)
      git_hash=$(git -C "$SNAPCRAFT_PROJECT_DIR" describe --always)
      craftctl set version="${cli_version#v}+${git_hash}"

  cli:
    source:
      - on amd64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.12/inference-snaps-cli-linux-amd64.tar.xz
      - on arm64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.12/inference-snaps-cli-linux-arm64.tar.xz
    plugin: dump
    override-build: |

      # For tab completion
      ln --symbolic ./modelctl bin/whisper-asr

      craftctl default
    
  cli-dependencies:
    plugin: nil
    stage-packages:
      - pciutils # lspci
      - clinfo # used for Intel GPU vRAM detection. It depends on intel-opencl-icd
      - coreutils # to have `nproc`

  cli-nvidia-smi:
    plugin: nil
    build-packages:
      - nvidia-utils-580
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/nvidia-smi $CRAFT_PART_INSTALL/usr/bin/
      
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc/nvidia-utils-580/
      mkdir -p $license_dir
      cp /usr/share/doc/nvidia-utils-580/copyright $license_dir/

  engines:
    source: engines
    plugin: dump
    organize:
      "*": engines/

  models:
    source: models
    plugin: dump
    organize:
      "*": models/

  runtimes:
    source: runtimes
    plugin: dump
    organize:
      "*": runtimes/

  local-component-files:
     # Use the cmake plugin instead of "dump" to prevent unwanted copies
     # See https://github.com/canonical/craft-parts/issues/1609
    plugin: cmake
    source: components
    override-build: |
      cp -rf --archive --link --no-dereference ${CRAFT_PART_SRC}/* ${CRAFT_PART_INSTALL}
    organize:
      "model-faster-whisper-base/*": (component/model-faster-whisper-base)
      "model-faster-whisper-small/*": (component/model-faster-whisper-small)
    prime:
      # Exclude everything not explicitly organized
      - -*

  myna-adapter:
    plugin: go
    source: .
    build-snaps:
      - go/1.26/stable

  whisper-live:
    plugin: python
    source: https://github.com/collabora/WhisperLive.git
    source-branch: main
    python-requirements: 
      - requirements/server.txt
    build-packages:
      - python3-dev
      - python3-venv
      - python3-pip
      - pkg-config
      - portaudio19-dev
      - wget
      - unzip
    stage-packages:
      - python3-minimal
    override-build: |
      craftctl default
      mv LICENSE ${CRAFT_PART_INSTALL}/usr/share/doc/WhisperLive

      move_packages_to_component() {
        local packages_filter="$1"
        local component_name="$2"

        local component_name_normalized=$(echo "$component_name" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
        local destination_component_env="CRAFT_COMPONENT_${component_name_normalized}_PRIME"
        local destination_component_dir="${!destination_component_env}"

        mkdir -p "$destination_component_dir/site-packages/"
        cp -arf --link "${CRAFT_PART_INSTALL}"/lib/python*/site-packages/${packages_filter} \
          "$destination_component_dir/site-packages/"
        rm -rf "${CRAFT_PART_INSTALL}"/lib/python*/site-packages/${packages_filter}
      }

      # Move CUDA python packages and CUDA-pytorch to a separate component
      move_packages_to_component "torch*" "whisper-live-cuda"
      move_packages_to_component "nvidia*" "whisper-live-cuda"
      move_packages_to_component "ctranslate2*" "whisper-live-cuda"

      # Install pytorch CPU and move it to the CPU component
      pip install ctranslate2
      pip install "torch==2.14.0+cpu" --index-url https://download.pytorch.org/whl/cpu
      move_packages_to_component "torch*" "whisper-live-cpu"
      move_packages_to_component "ctranslate2*" "whisper-live-cpu"

      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]; then # ROCm is only supported on AMD64

        # Install pytorch ROCm and ROCm-ctranslate2 and move them to the ROCm component
        pip install "torch==2.13.0+rocm7.2" --index-url https://download.pytorch.org/whl/rocm7.2
        move_packages_to_component "torch*" "whisper-live-rocm"

        # download and extract CTranslate2 ROCm wheels
        mkdir -p /tmp/rocm-wheels
        wget https://github.com/OpenNMT/CTranslate2/releases/download/v4.8.2/rocm-python-wheels-Linux.zip \
          -O /tmp/rocm-wheels/rocm-python-wheels-Linux.zip
        unzip /tmp/rocm-wheels/rocm-python-wheels-Linux.zip -d /tmp/rocm-wheels
        
        # let pip figure out which wheel to install based on the current environment
        pip install --no-index --find-links=/tmp/rocm-wheels/temp-linux ctranslate2
        move_packages_to_component "ctranslate2*" "whisper-live-rocm"
      fi
      
    organize:
      "*": (component/whisper-live)
  
  rocm-dependencies:
    plugin: nil
    stage-packages:
      - libatomic1
    override-pull: &amd64-only |
      [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ] && craftctl default || exit 0
    organize:
      "*": (component/whisper-live-rocm)

  notice:
    plugin: nil
    source: NOTICE
    source-type: file
    override-build: |
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc
      mkdir -p $license_dir
      cp NOTICE $license_dir/
      cp $SNAPCRAFT_PROJECT_DIR/LICENSE $license_dir/
      cp $SNAPCRAFT_PROJECT_DIR/LICENSE-whisper $license_dir/

components:
  model-faster-whisper-base:
    type: standard
    summary: OpenAI's Whisper-Base translated to the CTranslate2 format
    description: Model weights for OpenAI's Whisper-Base in the CTranslate2 format
  model-faster-whisper-small:
    type: standard
    summary: OpenAI's Whisper-Small translated to the CTranslate2 format
    description: Model weights for OpenAI's Whisper-Small in the CTranslate2 format

  whisper-live:
    type: standard
    summary: WhisperLive server for real-time transcription
    description: A WebSocket-based server performing real-time speech transcription using OpenAI's models.

  whisper-live-cpu:
    type: standard
    summary: WhisperLive dependencies for CPU inference
    description: Set of libraries to enable WhisperLive to use CPU for inference.

  whisper-live-cuda:
    type: standard
    summary: WhisperLive dependencies for CUDA inference
    description: Set of libraries to enable WhisperLive to use NVIDIA GPUs for inference.

  whisper-live-rocm:
    type: standard
    summary: WhisperLive dependencies for ROCm inference
    description: Set of libraries to enable WhisperLive to use AMD devices for inference.
  
apps:
  whisperlive-backend:
    command: bin/whisper-live-server
    daemon: simple
    plugs:
      - network
      - network-bind
      - opengl
      - hardware-observe

  server:
    command: bin/openai-adapter
    daemon: simple
    plugs:
      - network
      - network-bind

  whisper-asr:
    command: bin/whisper-asr
    completer: bin/snap-completer.bash
    plugs:
      - hardware-observe
      - opengl
      - network
