#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.install"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Set generic config
#

modelctl set --package engine-host="127.0.0.1"
modelctl set --package engine-port="9090"

modelctl set --package server-unix-socket="$SNAP_COMMON/openai.sock"


#
# Auto select an engine
#

modelctl use-engine --auto --components --assume-yes --fallback=cpu
